version: '3'
services: 
  creditcard-app:
    container_name: creditcard-app
    image: bharatht19/creditcard_app
    restart: on-failure
    ports: 
      - 10666:9090
    environment: 
      WAIT_HOSTS: mysql:3306
    depends_on: 
      - docker-mysql
      - creditscore-app
  creditscore-app:
    container_name: creditscore-app
    image: bharatht19/creditscore_app
    restart: on-failure
    ports: 
      - 10555:8080
    environment: 
      WAIT_HOSTS: mysql:3306
    depends_on: 
      - docker-mysql
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment: 
      MYSQL_DATABASE: creditdb
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_ROOT_HOST: '%'
    volumes: 
      - ./sql:/docker-entrypoint-initdb.d
    ports: 
      - 6666:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root password=test1234 --execute \"SHOW DATABASES \""
      interval: 4s
      timeout: 20s
      retries: 5